export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_PRODUCT_COUNT = "ADD_PRODUCT_COUNT";
export const SUB_PRODUCT_COUNT = "SUB_PRODUCT_COUNT";